import type { DatavElementMetadata } from '@datav-kit/core'

export const decoration11Metadata = {
  tagName: 'dvk-decoration-11',
  className: 'Decoration11Element',
  description: 'Cyber floating hollow halo stack with a raised inner ring, rotating neon arcs, segmented lower tick track, gold-white orbit lines, bridge glows, and sparse particles.',
  props: {
    color: {
      type: 'string',
      default: '',
      attribute: true,
      cssVariable: '--dvk-color-primary',
      description: 'Primary cyan neon color for bright rings, ticks, particles, bridge glows, and the dark center rim. Also accepts a DataV-compatible color array when set as a property.',
    },
    secondaryColor: {
      type: 'string',
      default: '',
      attribute: 'secondary-color',
      cssVariable: '--dvk-color-secondary',
      description: 'Secondary blue color for guide rings, lower tracks, segmented blocks, shadows, and cool bridge lines.',
    },
    colors: {
      type: 'string',
      default: '',
      attribute: true,
      description: 'Comma-separated primary, secondary, and optional gold accent colors.',
    },
    dur: {
      type: 'number',
      default: 9,
      attribute: true,
      description: 'Base rotation duration in seconds. Values are clamped to the 6-14 second floating-halo range.',
    },
    animated: {
      type: 'boolean',
      default: true,
      attribute: true,
      description: 'Enables rotating halo layers, orbit arcs, and particle drift animations.',
    },
    paused: {
      type: 'boolean',
      default: false,
      attribute: true,
      description: 'Stops all animations while keeping the raised layered platform visible.',
    },
  },
  events: [
    {
      name: 'dvk-ready',
      detail: '{ tagName }',
      description: 'Fired after the element first renders.',
    },
  ],
  parts: [
    'graphic',
    'ground-glow',
    'lift-shadow',
    'vertical-links',
    'bridge-line',
    'lift-layer',
    'base-layer',
    'lower-layer',
    'middle-layer',
    'inner-layer',
    'ring',
    'guide-ring',
    'core-guide',
    'lower-track',
    'bright-ring',
    'outer-bright',
    'lower-bright',
    'sweep-ring',
    'sweep-arc',
    'segmented-track',
    'segment-block',
    'ticks',
    'outer-ticks',
    'inner-ticks',
    'tick',
    'gold-orbit',
    'white-orbit',
    'core-disc',
    'inner-side-shadow',
    'inner-top-highlight',
    'inner-front-lip',
    'core-ticks',
    'core-tick',
    'core',
    'core-void',
    'void-hole',
    'void-rim',
    'particles',
    'particle',
  ],
} satisfies DatavElementMetadata
