import type { DatavElementMetadata } from '@datav-kit/core'

export const decoration11Metadata = {
  tagName: 'dvk-decoration-11',
  className: 'Decoration11Element',
  description: 'Cyber floating audio halo that can rasterize animated SVG into runtime media to avoid sustained SVG animation CPU cost.',
  props: {
    color: {
      type: 'string',
      default: '',
      attribute: true,
      cssVariable: '--dvk-color-primary',
      description: 'Primary cyan neon color for glow rings, scale ticks, audio rhythm blocks, bridge glows, and inner indicators. Also accepts a DataV-compatible color array when set as a property.',
    },
    secondaryColor: {
      type: 'string',
      default: '',
      attribute: 'secondary-color',
      cssVariable: '--dvk-color-secondary',
      description: 'Secondary blue color for guide rings, tick shadows, segmented arcs, and cool bridge lines.',
    },
    colors: {
      type: 'string',
      default: '',
      attribute: true,
      description: 'Comma-separated primary, secondary, and optional gold accent colors.',
    },
    dur: {
      type: 'number',
      default: 9,
      attribute: true,
      description: 'Base rotation duration in seconds. Values are clamped to the 6-14 second floating-halo range.',
    },
    animated: {
      type: 'boolean',
      default: true,
      attribute: true,
      description: 'Enables the fixed outer audio rhythm-block ring and selected inner layers to rotate.',
    },
    paused: {
      type: 'boolean',
      default: false,
      attribute: true,
      description: 'Stops all rotations while keeping the raised layered platform visible.',
    },
    videoRasterize: {
      type: 'boolean',
      default: true,
      attribute: 'video-rasterize',
      description: 'Enables runtime rasterization for the animated SVG. Set video-rasterize="false" to keep the live SVG animation path.',
    },
    rasterRenderer: {
      type: 'string',
      default: 'sprite',
      attribute: 'raster-renderer',
      description: 'Runtime raster output renderer. Defaults to "sprite" for a transparent PNG atlas with CSS steps playback; use "video" for WebM playback.',
    },
  },
  events: [
    {
      name: 'dvk-ready',
      detail: '{ tagName }',
      description: 'Fired after the element first renders.',
    },
    {
      name: 'dvk-raster-error',
      detail: '{ message }',
      description: 'Fired when runtime rasterization fails; the component keeps the SVG fallback visible.',
    },
  ],
  parts: [
    'graphic',
    'raster',
    'vertical-links',
    'bridge-line',
    'lift-layer',
    'particle-layer',
    'audio-bars',
    'audio-bar-ring',
    'thin-glow-layer',
    'thick-glow-layer',
    'thick-side-shadow',
    'scale-layer',
    'inner-segment-layer',
    'inner-layer',
    'ring',
    'guide-ring',
    'particle-guide',
    'thin-glow-ring',
    'thick-glow-ring',
    'scale-guide',
    'segment-guide',
    'dashed-ring',
    'bright-ring',
    'sweep-ring',
    'sweep-arc',
    'thin-sweep',
    'segmented-track',
    'segmented-ring',
    'segment-block',
    'segment-arc',
    'ticks',
    'scale-ticks',
    'tick',
    'scale-tick',
    'triangle-indicators',
    'triangle-indicator',
    'particles',
    'particle',
  ],
} satisfies DatavElementMetadata
