import type { DatavElementMetadata } from '@datav-kit/core'

export const title7Metadata = {
  tagName: 'dvk-title-7',
  className: 'Title7Element',
  description: 'Large-screen title banner whose side ribbons fold down through a shoulder into a flat bottom horizon, with a blurred centre beam on the horizon, a rail-capped node and a group of slash blades past each shoulder, and the title floating above the baseline.',
  props: {
    color: {
      type: 'string',
      default: '',
      attribute: true,
      cssVariable: '--dvk-color-primary',
      description: 'Primary cyan color for the lit end of each ribbon, the outer hairline, the rail caps and the bright end of the horizon. Also accepts a DataV-compatible color array when set as a property.',
    },
    secondaryColor: {
      type: 'string',
      default: '',
      attribute: 'secondary-color',
      cssVariable: '--dvk-color-secondary',
      description: 'Secondary deep navy color for the dim end of each ribbon, the side rails, the slash blades and the quiet ends of the horizon.',
    },
    accentColor: {
      type: 'string',
      default: '',
      attribute: 'accent-color',
      cssVariable: '--dvk-title-7-accent',
      description: 'Accent color for the white-hot centre of the horizon beam and the rail caps.',
    },
    colors: {
      type: 'string',
      default: '',
      attribute: true,
      description: 'Comma-separated primary, secondary, and accent colors.',
    },
    titleText: {
      type: 'string',
      default: '',
      attribute: 'title-text',
      description: 'Optional centered system name. When omitted, the default slot is rendered inside the title area.',
    },
  },
  events: [
    {
      name: 'dvk-ready',
      detail: '{ tagName }',
      description: 'Fired after the element first renders.',
    },
  ],
  parts: [
    'graphic',
    'ribbon',
    'ribbon-left',
    'ribbon-right',
    'diagonal',
    'diagonal-left',
    'diagonal-right',
    'diagonal-glow',
    'side-rail',
    'side-rail-left',
    'side-rail-right',
    'side-rail-dim',
    'slash',
    'slash-left',
    'slash-right',
    'slash-underline',
    'node',
    'node-left',
    'node-right',
    'node-highlight',
    'horizon',
    'horizon-flank',
    'horizon-flank-left',
    'horizon-flank-right',
    'horizon-beam',
    'beam',
    'beam-glow',
    'beam-core',
    'content',
    'title',
    'title-text',
  ],
} satisfies DatavElementMetadata
