import type { DatavElementMetadata } from '@datav-kit/core'

export const decoration10Metadata = {
  tagName: 'dvk-decoration-10',
  className: 'Decoration10Element',
  description: 'Futuristic HUD radar with concentric rings, precision ticks, a clockwise scanning beam, pulsing target points, sparse particles, restrained cyan-blue neon glow, and runtime rasterization for lower SVG animation CPU cost.',
  props: {
    color: {
      type: 'string',
      default: '',
      attribute: true,
      cssVariable: '--dvk-color-primary',
      description: 'Primary cyan neon color for radar rings, ticks, scanner edge, particles, and target cores. Also accepts a DataV-compatible color array when set as a property.',
    },
    secondaryColor: {
      type: 'string',
      default: '',
      attribute: 'secondary-color',
      cssVariable: '--dvk-color-secondary',
      description: 'Secondary blue color for grid lines, guide rings, data flow, and radar shadows.',
    },
    colors: {
      type: 'string',
      default: '',
      attribute: true,
      description: 'Comma-separated primary, secondary, and optional accent colors.',
    },
    dur: {
      type: 'number',
      default: 8,
      attribute: true,
      description: 'Clockwise scanner rotation duration in seconds. Values are clamped to the 6-10 second radar range.',
    },
    animated: {
      type: 'boolean',
      default: true,
      attribute: true,
      description: 'Enables scanner, pulse, flowing arc, ripple, and data-line animations.',
    },
    paused: {
      type: 'boolean',
      default: false,
      attribute: true,
      description: 'Stops all animations while keeping the static radar geometry visible.',
    },
    rasterRenderer: {
      type: 'string',
      default: 'sprite',
      attribute: 'raster-renderer',
      description: 'Runtime raster output renderer. Defaults to "sprite" for transparent PNG atlas playback on canvas; use "video" for WebM playback.',
    },
  },
  events: [
    {
      name: 'dvk-ready',
      detail: '{ tagName }',
      description: 'Fired after the element first renders.',
    },
    {
      name: 'dvk-raster-error',
      detail: '{ message }',
      description: 'Fired when runtime rasterization fails; the component keeps the SVG fallback visible.',
    },
  ],
  parts: [
    'graphic',
    'raster',
    'grid',
    'background-nodes',
    'background-node',
    'data-flow',
    'data-line',
    'ripple-grid',
    'signal-ripple',
    'halo',
    'radial-grid',
    'radial-line',
    'ring',
    'outer-ring',
    'inner-ring',
    'flow-ring',
    'flow-arc',
    'segmented-ring',
    'ticks',
    'tick',
    'particles',
    'particle',
    'scanner',
    'scan-beam',
    'scan-edge',
    'targets',
    'target',
    'target-ripple',
    'target-core',
    'center',
    'center-pulse',
    'content',
  ],
} satisfies DatavElementMetadata
