export { BorderBox1Element } from './border-box-1/element'
export { borderBox1Metadata } from './border-box-1/metadata'
export { defineBorderBox1 } from './border-box-1/register'
export { FitScreenElement } from './fit-screen/element'
export { fitScreenMetadata } from './fit-screen/metadata'
export { defineFitScreen } from './fit-screen/register'
export { elementMetadata, type ElementMetadata } from './metadata'
export { datavElementRegistrations, register } from './register'
