import type { DatavElementMetadata } from '@datav-kit/core'

export const title8Metadata = {
  tagName: 'dvk-title-8',
  className: 'Title8Element',
  description: 'Large-screen title banner whose upper rails run in from each edge through a shoulder onto a luminous spine, around a dark recess lit by two ambient blooms, with slash blades and an end dot matrix past each shoulder, and the title set in a white-to-blue glyph ramp above the spine.',
  props: {
    color: {
      type: 'string',
      default: '',
      attribute: true,
      cssVariable: '--dvk-color-primary',
      description: 'Primary cyan color for the bright end of the upper rails and the flanks of the spine. Also accepts a DataV-compatible color array when set as a property.',
    },
    secondaryColor: {
      type: 'string',
      default: '',
      attribute: 'secondary-color',
      cssVariable: '--dvk-color-secondary',
      description: 'Secondary deep navy color for the dim end of the upper rails and the band, the lower rails, the slash blades and the quiet ends of the spine.',
    },
    accentColor: {
      type: 'string',
      default: '',
      attribute: 'accent-color',
      cssVariable: '--dvk-title-8-accent',
      description: 'Accent color for the white-hot centre of the spine.',
    },
    colors: {
      type: 'string',
      default: '',
      attribute: true,
      description: 'Comma-separated primary, secondary, and accent colors.',
    },
    titleText: {
      type: 'string',
      default: '',
      attribute: 'title-text',
      description: 'Optional centered system name. When omitted, the default slot is rendered inside the title area.',
    },
  },
  events: [
    {
      name: 'dvk-ready',
      detail: '{ tagName }',
      description: 'Fired after the element first renders.',
    },
  ],
  parts: [
    'graphic',
    'bloom',
    'band',
    'band-left',
    'band-right',
    'recess',
    'recess-left',
    'recess-right',
    'upper-rail',
    'upper-rail-left',
    'upper-rail-right',
    'upper-rail-glow',
    'upper-rail-core',
    'lower-rail',
    'lower-rail-left',
    'lower-rail-right',
    'slash',
    'slash-left',
    'slash-right',
    'dots',
    'dots-left',
    'dots-right',
    'aura',
    'spine',
    'spine-glow',
    'spine-core',
    'content',
    'title',
    'title-text',
  ],
} satisfies DatavElementMetadata
