import type { DatavElementMetadata } from '@datav-kit/core'

export const decoration8Metadata = {
  tagName: 'dvk-decoration-8',
  className: 'Decoration8Element',
  description: 'Futuristic rotating HUD energy ring that can rasterize animated SVG into runtime media to avoid sustained SVG animation CPU cost.',
  props: {
    color: {
      type: 'string',
      default: '',
      attribute: true,
      cssVariable: '--dvk-color-primary',
      description: 'Primary neon ring, tick, and energy block color. Also accepts a DataV-compatible color array when set as a property.',
    },
    secondaryColor: {
      type: 'string',
      default: '',
      attribute: 'secondary-color',
      cssVariable: '--dvk-color-secondary',
      description: 'Secondary arc, guide, and micro indicator color.',
    },
    colors: {
      type: 'string',
      default: '',
      attribute: true,
      description: 'Comma-separated primary and secondary colors.',
    },
    dur: {
      type: 'number',
      default: 5,
      attribute: true,
      description: 'Rotation duration in seconds.',
    },
    animated: {
      type: 'boolean',
      default: true,
      attribute: true,
      description: 'Enables SVG rotation animations.',
    },
    paused: {
      type: 'boolean',
      default: false,
      attribute: true,
      description: 'Stops rotation animations while keeping the static geometry visible.',
    },
    videoRasterize: {
      type: 'boolean',
      default: true,
      attribute: 'video-rasterize',
      description: 'Enables runtime rasterization for the animated SVG. Set video-rasterize="false" to keep the live SVG animation path.',
    },
    rasterRenderer: {
      type: 'string',
      default: 'sprite',
      attribute: 'raster-renderer',
      description: 'Runtime raster output renderer. Defaults to "sprite" for transparent PNG atlas playback on canvas; use "video" for WebM playback.',
    },
  },
  events: [
    {
      name: 'dvk-ready',
      detail: '{ tagName }',
      description: 'Fired after the element first renders.',
    },
    {
      name: 'dvk-raster-error',
      detail: '{ message }',
      description: 'Fired when runtime rasterization fails; the component keeps the SVG fallback visible.',
    },
  ],
  parts: [
    'graphic',
    'raster',
    'background',
    'halo',
    'ring',
    'outer-ring',
    'outer-trace',
    'inner-ring',
    'outer-arcs',
    'outer-arc-band',
    'outer-arc-trace',
    'segmented-track',
    'guide-ring',
    'outer-guide',
    'inner-guide',
    'core-guide',
    'ticks',
    'tick',
    'energy-blocks',
    'energy-block',
    'micro-lights',
    'micro-light',
    'core',
    'content',
  ],
} satisfies DatavElementMetadata
