import type { DatavElementMetadata } from '@datav-kit/core'

export const title6Metadata = {
  tagName: 'dvk-title-6',
  className: 'Title6Element',
  description: 'Large-screen title banner whose horizon runs into a shoulder on each side and up to a long upper rail, with translucent diagonal ribbons and support rails past the shoulders, around a white-hot centre core.',
  props: {
    color: {
      type: 'string',
      default: '',
      attribute: true,
      cssVariable: '--dvk-color-primary',
      description: 'Primary blue color for the bright end of the upper rails, the outer ticks and the horizon halo. Also accepts a DataV-compatible color array when set as a property.',
    },
    secondaryColor: {
      type: 'string',
      default: '',
      attribute: 'secondary-color',
      cssVariable: '--dvk-color-secondary',
      description: 'Secondary deep blue color for the dim end of the upper rails, the ribbons, the support rails and the quiet ends of the horizon.',
    },
    accentColor: {
      type: 'string',
      default: '',
      attribute: 'accent-color',
      cssVariable: '--dvk-title-6-accent',
      description: 'Accent color for the white-hot centre of the horizon.',
    },
    colors: {
      type: 'string',
      default: '',
      attribute: true,
      description: 'Comma-separated primary, secondary, and accent colors.',
    },
    titleText: {
      type: 'string',
      default: '',
      attribute: 'title-text',
      description: 'Optional centered system name. When omitted, the default slot is rendered inside the title area.',
    },
  },
  events: [
    {
      name: 'dvk-ready',
      detail: '{ tagName }',
      description: 'Fired after the element first renders.',
    },
  ],
  parts: [
    'graphic',
    'ribbon',
    'ribbon-left',
    'ribbon-right',
    'rail',
    'rail-left',
    'rail-right',
    'rail-glow',
    'rail-core',
    'support-rail',
    'support-rail-left',
    'support-rail-right',
    'tick',
    'tick-bright',
    'tick-dim',
    'horizon',
    'horizon-glow',
    'horizon-core',
    'horizon-halo',
    'core',
    'core-blur',
    'core-line',
    'content',
    'title',
    'title-text',
  ],
} satisfies DatavElementMetadata
